version: "3.7"

services:
  runner:
    image: myoung34/github-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      RUNNER_SCOPE: repo
      RUNNER_NAME_PREFIX: myrunner
      LABELS: local-runner
      REPO_URL: https://github.com/mengoaingu/mengoaingu
      EPHEMERAL: 1
      ACCESS_TOKEN: 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
    # deploy:
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G
    #     reservations:
    #       cpus: '0.2'
    #       memory: 256M