version: "3.7"

services:
  mysqld:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456" ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 10s
    image: mysql:8.0
    platform: linux/amd64
    logging:
      options:
        max-size: 10m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      # Avoid writable bind mount
      - "./.bin/data/mysql:/var/lib/mysql"
      - "./.bin/assets/mysql:/docker-entrypoint-initdb.d"
    restart: always

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    hostname: broker
    depends_on:
      - zookeeper
    
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

      
networks:
  mengoaingu-network:


    # schema-registry:
  #   image: confluentinc/cp-schema-registry:7.0.1
  #   platform: linux/amd64
  #   logging:
  #     options:
  #       max-size: 10m
  #   depends_on:
  #     - broker
  #   environment:
  #     SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx128M -Xms128M"
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
  #     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  # connect:
  #   image: debezium/connect:1.8.0.Final
  #   platform: linux/amd64
  #   logging:
  #     options:
  #       max-size: 10m
  #   depends_on:
  #     - broker
  #     - schema-registry
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     HEAP_OPTS: "-Xmx256M -Xms128M"
  #     GROUP_ID: debezium-connect-group
  #     CONFIG_STORAGE_TOPIC: debezium-connect-configs
  #     OFFSET_STORAGE_TOPIC: debezium-connect-offsets
  #     ADVERTISED_HOST_NAME: connect
  #     BOOTSTRAP_SERVERS: 'broker:29092'
  #     REST_ADVERTISED_HOST_NAME: connect
  #     CONFIG_STORAGE_REPLICATION_FACTOR: 1
  #     OFFSET_FLUSH_INTERVAL_MS: 10000
  #     OFFSET_STORAGE_REPLICATION_FACTOR: 1
  #     STATUS_STORAGE_TOPIC: debezium-connect-status
  #     STATUS_STORAGE_REPLICATION_FACTOR: 1
  #     VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  #     LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR