# docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:2.9.3

version: "3.7"

services:

  portainer:
    image: portainer/portainer-ce:2.9.3
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: mengoaingu-nw
    external: true

volumes:
  portainer_data:
    external: true