version: "3.7"

services:
  web:
    image: playlistduong/mengoaingu:web
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    # deploy:
    #   replicas: 2
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G
networks:
  default:
    name: mengoaingu-nw
    external: true