version: "3.7"

services:

  mysql:
    image: mysql:8.0
    hostname: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

networks:
  default:
    name: mengoaingu-nw
    external: true

volumes:
  dbdata:
    external: true