name: Mengoaingu
run-name: ${{ github.actor }} is deploying GitHub Actions 🚀
on:
  push:
    paths:
      - webui/**
    branches:
      - main
jobs:
  build:
    runs-on: [local-runner]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker --version
      - run: docker build --no-cache -t playlistduong/mengoaingu:web -f docker/dockerfiles/web.Dockerfile .
      - run: docker push playlistduong/mengoaingu:web

  deploy:
    runs-on: [prd-runner]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker stack deploy --with-registry-auth -c docker/services/web.yaml mengoaingu